"""Add supervisor change request model

Revision ID: 14f43774fbec
Revises: f16c25623a0c
Create Date: 2025-11-07 09:52:56.304224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f43774fbec'
down_revision = 'f16c25623a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=False),
    sa.Column('current_supervisor_id', sa.Integer(), nullable=False),
    sa.Column('new_supervisor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_supervisor_status', sa.String(length=20), nullable=True),
    sa.Column('current_supervisor_comment', sa.Text(), nullable=True),
    sa.Column('current_supervisor_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('new_supervisor_status', sa.String(length=20), nullable=True),
    sa.Column('new_supervisor_comment', sa.Text(), nullable=True),
    sa.Column('new_supervisor_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('dean_status', sa.String(length=20), nullable=True),
    sa.Column('dean_comment', sa.Text(), nullable=True),
    sa.Column('dean_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('dean_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_supervisor_id'], ['supervisors.id'], ),
    sa.ForeignKeyConstraint(['dean_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_supervisor_id'], ['supervisors.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supervisor_change_requests')
    # ### end Alembic commands ###
