"""Add scholar_comment to meetings

Revision ID: 68fe592bbc2c
Revises: d004c8510505
Create Date: 2025-11-11 00:44:21.006323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fe592bbc2c'
down_revision = 'd004c8510505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scholar_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('scholar_comment')

    # ### end Alembic commands ###
