"""Add personal_email to supervisors

Revision ID: 8144a07649a6
Revises: 09486cca1204
Create Date: 2025-11-15 13:45:43.741937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8144a07649a6'
down_revision = '09486cca1204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.drop_column('personal_email')

    # ### end Alembic commands ###
