"""Add personal_email to scholars

Revision ID: b8d9e6f3a1c2
Revises: ac682c4812af
Create Date: 2025-11-08 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d9e6f3a1c2'
down_revision = 'ac682c4812af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholars', sa.Column('personal_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholars', 'personal_email')
    # ### end Alembic commands ###
