"""Add thesis defense workflow with external examiners and degree completion

Revision ID: b966e6ff82c4
Revises: 900693dfc2ed
Create Date: 2025-11-12 13:32:28.334828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b966e6ff82c4'
down_revision = '900693dfc2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create examiners table
    op.create_table('examiners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('specialization', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiners_email'), 'examiners', ['email'], unique=True)

    # Rename thesis to thesis_submissions and add new columns
    op.rename_table('thesis', 'thesis_submissions')

    with op.batch_alter_table('thesis_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_examiner_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # Create thesis_examiners junction table
    op.create_table('thesis_examiners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('examiner_id', sa.Integer(), nullable=False),
    sa.Column('examiner_role', sa.String(length=50), nullable=True),
    sa.Column('invitation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invitation_status', sa.String(length=50), nullable=True),
    sa.Column('report_submitted', sa.Boolean(), nullable=True),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('report_file_name', sa.String(length=255), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create thesis_defenses table
    op.create_table('thesis_defenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('defense_date', sa.Date(), nullable=False),
    sa.Column('defense_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('committee_comments', sa.Text(), nullable=True),
    sa.Column('conducted_by', sa.Integer(), nullable=True),
    sa.Column('committee_members', sa.Text(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create progress_report_reminders table
    op.create_table('progress_report_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('first_reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('first_reminder_date', sa.DateTime(), nullable=True),
    sa.Column('second_reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('second_reminder_date', sa.DateTime(), nullable=True),
    sa.Column('final_reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('final_reminder_date', sa.DateTime(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('progress_report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['progress_report_id'], ['progress_reports.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_report_approvals', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reviewer_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('progress_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('progress_reports_reviewed_by_fkey'), type_='foreignkey')
        batch_op.drop_column('feedback')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')

    with op.batch_alter_table('scholars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defense_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('degree_awarded_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('final_result', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('thesis_defense_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('travel_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grant_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('event_name', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('organizers', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('venue_country', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('invitation_letter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('broad_area', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('reasons_for_visit', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('funds_from_other_agencies', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('institute_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('institute_reasons', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('funding_agency_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('sanctioned_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('registration_waiver_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registration_waiver_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('funds_from_supervisor_grant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_grant_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('anticipated_expenses', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('other_financial_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('presenting_paper', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paper_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('number_of_papers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paper_other_details', sa.Text(), nullable=True))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('supporting_document')
        batch_op.drop_column('destination')
        batch_op.drop_column('purpose')
        batch_op.drop_column('conference_name')
        batch_op.drop_column('amount_requested')
        batch_op.drop_column('acceptance_letter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_letter', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount_requested', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('conference_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('supporting_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('paper_other_details')
        batch_op.drop_column('paper_links')
        batch_op.drop_column('number_of_papers')
        batch_op.drop_column('paper_title')
        batch_op.drop_column('presenting_paper')
        batch_op.drop_column('other_financial_details')
        batch_op.drop_column('anticipated_expenses')
        batch_op.drop_column('supervisor_grant_amount')
        batch_op.drop_column('funds_from_supervisor_grant')
        batch_op.drop_column('registration_waiver_document')
        batch_op.drop_column('registration_waiver_requested')
        batch_op.drop_column('sanctioned_amount')
        batch_op.drop_column('funding_agency_name')
        batch_op.drop_column('institute_reasons')
        batch_op.drop_column('institute_amount')
        batch_op.drop_column('funds_from_other_agencies')
        batch_op.drop_column('reasons_for_visit')
        batch_op.drop_column('broad_area')
        batch_op.drop_column('invitation_letter')
        batch_op.drop_column('venue_country')
        batch_op.drop_column('organizers')
        batch_op.drop_column('event_name')
        batch_op.drop_column('grant_type')

    with op.batch_alter_table('scholars', schema=None) as batch_op:
        batch_op.drop_column('thesis_defense_status')
        batch_op.drop_column('final_result')
        batch_op.drop_column('degree_awarded_date')
        batch_op.drop_column('defense_completion_date')

    with op.batch_alter_table('progress_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('progress_reports_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'])

    with op.batch_alter_table('progress_report_approvals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('reviewer_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('thesis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scholar_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submission_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('defense_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('defense_venue', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('defense_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_examiner_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('external_examiner_institution', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('external_examiner_report', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('thesis_reviewed_by_fkey')),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], name=op.f('thesis_scholar_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('thesis_pkey'))
    )
    op.drop_table('progress_report_reminders')
    op.drop_table('thesis_submissions')
    # ### end Alembic commands ###
