"""Add suspension fields to scholars

Revision ID: c9a2d7e4b3f1
Revises: b8d9e6f3a1c2
Create Date: 2025-11-08 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a2d7e4b3f1'
down_revision = 'b8d9e6f3a1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholars', sa.Column('suspension_start_date', sa.Date(), nullable=True))
    op.add_column('scholars', sa.Column('suspension_end_date', sa.Date(), nullable=True))
    op.add_column('scholars', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('scholars', sa.Column('is_rusticated', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('scholars', sa.Column('rustication_date', sa.Date(), nullable=True))
    op.add_column('scholars', sa.Column('rustication_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholars', 'rustication_reason')
    op.drop_column('scholars', 'rustication_date')
    op.drop_column('scholars', 'is_rusticated')
    op.drop_column('scholars', 'suspension_reason')
    op.drop_column('scholars', 'suspension_end_date')
    op.drop_column('scholars', 'suspension_start_date')
    # ### end Alembic commands ###
